name: Test

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
      - run: npm run build
